### ISSUE TITLE
 Unknown vision tower: ./PCIResearch/TransCore-M/./openai/clip-vit-large-patch14-336

### ISSUE THREAD

**Issue by zhanghaobucunzai** [PCIResearch/TransCore-M#2]
CUDA_VISIBLE_DEVICES=0 python3 inference.py --model-path ./PCIResearch/TransCore-M --vision-path ./openai/clip-vit-large-patch14-336
You are using a model of type transcorem to instantiate a model of type TransCoreM. This is not supported for all configurations of models and can yield errors.
11111111111111111111111111111 False
222222222222222222222222222222 ./PCIResearch/TransCore-M/./openai/clip-vit-large-patch14-336
Traceback (most recent call last):
  File "inference.py", line 31, in <module>
    output_result = eval_model(args_params)
  File "/home/swx689421/TransCore-M-main/transcorem/eval/run_transcorem.py", line 31, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(args_params["model_path"], args_params["model_base"], model_name)
  File "/home/swx689421/TransCore-M-main/transcorem/model/builder.py", line 31, in load_pretrained_model
    model = TransCoreMLlamaForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 3462, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/swx689421/TransCore-M-main/transcorem/model/language_model/transcorem_llama.py", line 32, in __init__
    self.model = TransCoreMLlamaModel(config)
  File "/home/swx689421/TransCore-M-main/transcorem/model/language_model/transcorem_llama.py", line 24, in __init__
    super(TransCoreMLlamaModel, self).__init__(config)
  File "/home/swx689421/TransCore-M-main/transcorem/model/transcorem_core.py", line 18, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=True)
  File "/home/swx689421/TransCore-M-main/transcorem/model/multimodal_encoder/builder.py", line 20, in build_vision_tower
    raise ValueError(f'Unknown vision tower: {vision_tower}')
ValueError: Unknown vision tower: ./PCIResearch/TransCore-M/./openai/clip-vit-large-patch14-336

**Comment by zhanghaobucunzai** [comment]
已经解决
